name: Docker Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

steps:
  - name: Checkout repository
    uses: actions/checkout@v2
  - name: Setup Docker
    uses: docker/setup-docker@v1

  - name: Build Docker image
    run: docker build -t my-app ./api

  - name: Run PHPUnit tests
    run: docker run my-app php vendor/bin/phpunit

  - name: Publish test results
    uses: actions/upload-artifact@v2
    with:
      name: test-results
      path: ./tests-results/