name: build_docker

on:
  push:
    branches:
      - 'main'
env:
  CONTAINER_REGISTRY: 619865778916.dkr.ecr.eu-central-1.amazonaws.com
  IMAGE_MAIN_TAG: symfony-skeleton:main
  IMAGE_TEST_TAG: symfony-skeleton:testing
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
       -
         name: Set up QEMU
         uses: docker/setup-qemu-action@v2
       -
         name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
       -
         name: Login to ECR
         uses: docker/login-action@v3
         with:
           registry: ${{ env.CONTAINER_REGISTRY }}
           username: ${{ secrets.AWS_ECR_ACCESS_KEY }}
           password: ${{ secrets.AWS_ECR_SECRET }}
       -
         name: Build image
         uses: docker/build-push-action@v4
         with:
           context: "{{defaultContext}}:api"
           tags: ${{ env.IMAGE_TEST_TAG }}
           load: true
       -
         name: Run tests
         run: |
           docker run --rm ${{ env.IMAGE_TEST_TAG }} ./vendor/bin/phpunit
       -
         name: Push image
         uses: docker/build-push-action@v4
         with:
           context: "{{defaultContext}}:api"
           tags: "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_MAIN_TAG }}"
           push: true
           provenance: false
