name: deployment

on:
  workflow_run:
    workflows: [build_docker]
    types:
      - completed
jobs:
  deploy-ecs:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
       -
         name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
           aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_KEY }}
           aws-secret-access-key: ${{ secrets.AWS_ECR_SECRET }}
           aws-region: eu-central-1
       -
         name: Redeploy ECS service
         uses: donaldpiret/ecs-deploy@master
         with:
           cluster: symfony-skeleton
           target: symfony-skeleton-service-v3
