name: ci

on:
  push:
    branches:
      - 'main'
env:
  IMAGE_NAME: wazowski11/symfony-skeleton:main
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build image
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:api"
          tags: ${{ env.IMAGE_NAME }}
      -
        name: Run tests
        run: |
          docker run -it ${{ env.IMAGE_NAME }} ./vendor/bin/phpunit
      -
        name: Push image
        uses: docker/build-push-action@v4
        with:
          image: ${{ env.IMAGE_NAME }}
          
  deploy-prod:
    needs: build-docker
    runs-on: ubuntu-latest
    steps:
      - 
        name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            docker stop webapp || true
            docker rm webapp || true
            docker pull ${{ env.IMAGE_NAME }}
            docker run -d --name webapp -p 80:80 ${{ env.IMAGE_NAME }}
      
