name: ci

on:
  push:
    branches:
      - 'main'
env:
  IMAGE_NAME: wazowski11/symfony-skeleton:main
jobs:
  # docker:
  #   runs-on: ubuntu-latest
  #   steps:
  #     -
  #       name: Set up QEMU
  #       uses: docker/setup-qemu-action@v2
  #     -
  #       name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2
  #     -
  #       name: Login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_PASSWORD }}
  #     -
  #       name: Build and push
  #       uses: docker/build-push-action@v4
  #       with:
  #         context: "{{defaultContext}}:api"
  #         push: true
  #         tags: wazowski11/symfony-skeleton:main
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            docker stop webapp || true
            docker rm webapp || true
            docker pull ${{ env.IMAGE_NAME }}
            docker run -d --name webapp -p 80:80 ${{ env.IMAGE_NAME }}
      
