name: run_tests

on:
  pull_request:
jobs:
 unit-tests:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
      with:
        args: "-d api"
    - name: PHPUnit Tests
      uses: php-actions/phpunit@master
      with:
        version: 9.6
        configuration: api/phpunit.xml.dist
