name: run_tests

on:
  push:
    branches:
      - 'main'
jobs:
 unit-tests:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
      with:
        container_workdir: api
    - name: PHPUnit Tests
      uses: php-actions/phpunit@master
      with:
        version: 9.6
        bootstrap: /api/vendor/autoload.php
        configuration: /api/phpunit.xml
